#Huge s/o to pauseforasecond for the spreadsheet based on the BuzzFeed show Is It Worth It.
USE javaProjects;
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Sushi Stop','Bluefin Nigiri','USA','Los Angeles','$3 Sushi vs $250 Sushi','1','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Hamasaku','Kinmedai White Ponzu,Nigiri Platter,Cajun Crab Roll','USA','Los Angeles','$3 Sushi vs $250 Sushi','1','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Sasabune','Omakase','USA','Los Angeles','$3 Sushi vs $250 Sushi','1','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Habit Burger','Double Charburger','USA','Las Vegas','$4 Burger vs $777 Burger','1','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Gordon Ramsay Burgr','Hog Burger','USA','Las Vegas','$4 Burger vs $777 Burger','1','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Burger Brasserie','777 Burger','USA','Las Vegas','$4 Burger vs $777 Burger','1','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Blaze Pizza','Simple Pie','USA','Los Angeles','$5 Pizza vs $135 Pizza','1','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Pizzeria Mozza','Squash Blossoms','USA','Los Angeles','$5 Pizza vs $135 Pizza','1','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Spago','Italian Summer Truffle','USA','Los Angeles','$5 Pizza vs $135 Pizza','1','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Uncle John\'s Cafe','Steak and Eggs','USA','Los Angeles','$11 Steak vs $306 Steak','1','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Nick & Stef\'s Steakhouse','Dry-Aged Rib Eye','USA','Los Angeles','$11 Steak vs $306 Steak','1','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Cut','Japanese Pure Wagyu','USA','Los Angeles','$11 Steak vs $306 Steak','1','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Pasta Sisters','Tagliatella Arrabbiata','USA','Los Angeles','$8 Pasta vs $100 Pasta','1','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Osteria Mamma','Bigoli Neri Alla Bottarga','USA','Los Angeles','$8 Pasta vs $100 Pasta','1','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Le Petit Paris','Flambeed White Truffle Pasta','USA','Los Angeles','$8 Pasta vs $100 Pasta','1','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Vicious Dogs','Kosher Dog','USA','Los Angeles','$2 Hot Dog vs $169 Hot Dog','1','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Wurstküche','Lamb with Mediterranean Spices','USA','Los Angeles','$2 Hot Dog vs $169 Hot Dog','1','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Tokyo Dog','Juuni Ban','USA','Seattle','$2 Hot Dog vs $169 Hot Dog','1','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Emerald City Fish & Chips','Salmon Fish & Chips','USA','Seattle','$8 Salmon vs $56 Salmon','1','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Ivar\'s Salmon House','Chinook King Salmon','USA','Seattle','$8 Salmon vs $56 Salmon','1','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Aqua By El Gaucho','King Salmon','USA','Seattle','$8 Salmon vs $56 Salmon','1','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('OO-KOOK','Korean BBQ','USA','Los Angeles','$24 Korean BBQ vs $346 Korean BBQ','1','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Quarters','Korean BBQ','USA','Los Angeles','$24 Korean BBQ vs $346 Korean BBQ','1','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Chosun Galbee','Korean BBQ','USA','Los Angeles','$24 Korean BBQ vs $346 Korean BBQ','1','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Porto\'s Bakery','Milk\'n Berries Cake','USA','Los Angeles','$27 Cake vs $1120 Cake','1','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Proof Bakery','Chocolate Espresso Cake','USA','Los Angeles','$27 Cake vs $1120 Cake','1','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Bottega Louie','Custom Cake','USA','Los Angeles','$27 Cake vs $1120 Cake','1','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Blinkie\'s Donut Emporium','Glazed Donut','USA','Los Angeles','$1 Donut vs $100 Donut','2','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Church Key [CLOSED]','Brioche Donuts','USA','Los Angeles','$1 Donut vs $100 Donut','2','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Birdies','Golden Donut','USA','Los Angeles','$1 Donut vs $100 Donut','2','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Feast Buffet Red Rock Casino','Buffet Food','USA','Las Vegas','$7 Buffet vs $95 Buffet','2','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Wicked Spoon The Cosmopolitan','Buffet Food','USA','Las Vegas','$7 Buffet vs $95 Buffet','2','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Sterling Brunch BLT Steak at Bally\'s','Buffet Food','USA','Las Vegas','$7 Buffet vs $95 Buffet','2','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Leo\'s Taco Truck','Tacos Al Pastor','USA','Los Angeles','$47 Taco vs $1 Taco','2','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Guisados','Calabacitas,Mole Poblano,Cochinita Pibil','USA','Los Angeles','$47 Taco vs $1 Taco','2','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Rose. Rabbit. Lie','Caviar Taco','USA','Las Vegas','$47 Taco vs $1 Taco','2','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Foster\'s Freeze','Small Dipped Cone','USA','Los Angeles','$1 Ice Cream vs $1000 Ice Cream','2','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Scoops','One Scoop Brown Bread Maple Black Truffle','USA','Los Angeles','$1 Ice Cream vs $1000 Ice Cream','2','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Serendipity 3','Golden Opulence Sundae','USA','New York City','$1 Ice Cream vs $1000 Ice Cream','2','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Joe\'s Pizza','Cheese Slice','USA','New York City','$2 Pizza vs $2000 Pizza','2','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Rossopomodoro Eataly Flatiron','Marinara Pizza','USA','New York City','$2 Pizza vs $2000 Pizza','2','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Industry Kitchen','The 24K','USA','New York City','$2 Pizza vs $2000 Pizza','2','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Eileen\'s Special Cheesecake','Classic Cheesecake','USA','New York City','$4 Cheesecake vs $70 Cheesecake','2','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('STK Downtown','Orange Dream Cheesecake','USA','New York City','$4 Cheesecake vs $70 Cheesecake','2','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Lady M','Gateu Nuage','USA','New York City','$4 Cheesecake vs $70 Cheesecake','2','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Shake Shack','Peanut Butter Bacon Burger','USA','New York City','$7 Secret Menu vs $2500 Secret Menu','2','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Gramercy Tavern','Off-Menu Bacon Burger','USA','New York City','$7 Secret Menu vs $2500 Secret Menu','2','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Petrossian','Caviar Souffle','USA','New York City','$7 Secret Menu vs $2500 Secret Menu','2','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Good Times at Davey Wayne\'s','Davey\'s Old Fashioned','USA','Los Angeles','$6 Cocktail vs $208 Cocktail','2','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Pacific Seas @ Clifton\'s','Scorpion Bowl','USA','Los Angeles','$6 Cocktail vs $208 Cocktail','2','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('£10 @ The Montage Hotel','Penicillin','USA','Los Angeles','$6 Cocktail vs $208 Cocktail','2','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Lao Tao','Oolong Tea-Infused Egg','USA','Los Angeles','$2 Egg vs $95 Egg','2','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Connie and Ted\'s','Peeky Toe Crab & Lobster Omelette','USA','Los Angeles','$2 Egg vs $95 Egg','2','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Mélisse','Truggle Egg','USA','Los Angeles','$2 Egg vs $95 Egg','2','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Gangnam Galmegi','Beef Rib Finger Meat','Korea','Seoul','$13 BBQ Ribs vs $256 BBQ Ribs','2','10');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('So Deul Nyuk','Soy Marinated Beef Ribs','Korea','Seoul','$13 BBQ Ribs vs $256 BBQ Ribs','2','10');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Walkerhill Myongwolgwan','Hanwoo \'Byeongpung\' Beef Ribs','Korea','Seoul','$13 BBQ Ribs vs $256 BBQ Ribs','2','10');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Chef Marilyn\'s','Mac & Cheese','USA','Los Angeles','$3 Mac \'n Cheese vs $195 Mac \'n Cheese','3','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Little Jewel of New Orleans','Craw Mac Deluxe','USA','Los Angeles','$3 Mac \'n Cheese vs $195 Mac \'n Cheese','3','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Barton G.','Truffle Lobster Mac & Cheese','USA','Los Angeles','$3 Mac \'n Cheese vs $195 Mac \'n Cheese','3','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Bigmista\'s Barbecue & Sammich Shop','1/2 lb Pork Spare Ribs','USA','Long Beach','$7 BBQ Ribs vs $68 BBQ Ribs','3','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Barrel & Ashes','Pork Spare Ribs','USA','Studio City','$7 BBQ Ribs vs $68 BBQ Ribs','3','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Maple Block Meat Co','Full Rack Pork Spare Ribs','USA','Culver City','$7 BBQ Ribs vs $68 BBQ Ribs','3','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Doyle\'s Oyster Bar','Coffin Bay Oyster,Sydney Rock Oyster','Australia','Sydney','$3 Seafood vs $213 Seafood','3','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Cirrus','Grilled WA Marren','Australia','Sydney','$3 Seafood vs $213 Seafood','3','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Silks','Braised Whole Green Lip Abalone','Australia','Melbourne','$3 Seafood vs $213 Seafood','3','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Tahbilk Winery','2016 Marsanne','Australia','Nagambie','$18 Wine vs $1000 Wine','3','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Fowles Wine','Ladies Who Shoot Their Lunch 2016 Shiraz','Australia','Avenel','$18 Wine vs $1000 Wine','3','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('All Saints Estate Winery','Museum Muscadelle,Museum Muscat','Australia','Wahgunyah','$18 Wine vs $1000 Wine','3','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Clovelly Hotel','250g Rump Steak with Beans and Mash','Australia','Sydney','$16 Steak vs $150 Steak','3','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Donovan\'s','500g Grass Fed T-Bone','Australia','Melbourne','$16 Steak vs $150 Steak','3','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Rockpool Bar & Grill','Eye of Chuck Wagyu Ox','Australia','Sydney','$16 Steak vs $150 Steak','3','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Sylvia\'s Restaurant','Sylvia\'s Down Home Fried Chicken','USA','New York City','$17 Fried Chicken vs $500 Fried Chicken','3','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Red Rooster','Hot Honey Yard Bird','USA','New York City','$17 Fried Chicken vs $500 Fried Chicken','3','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Momofuku Noodle Bar','Caviar & Fried Chicken','USA','New York City','$17 Fried Chicken vs $500 Fried Chicken','3','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Homestead','Trinity,Blanco,Pecos,Lil Queso,Iced Toddy L','USA','Los Angeles','$19 Brunch vs $113 Brunch','3','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('A-Frame','All You Can Drink,All You Can Eat Stacks on Stacks','USA','Culver City','$19 Brunch vs $113 Brunch','3','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Belvedere','Brunch Buffet,Free Flow Champagne','USA','Los Angeles','$19 Brunch vs $113 Brunch','3','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Rinrin','Ramen','Japan','Tokyo','$3 Ramen vs $79 Ramen','3','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Tsuta Japanese Soba Noodles','Shobu Soba','Japan','Tokyo','$3 Ramen vs $79 Ramen','3','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Genei Tokyo','Ultimate Ramen & Highest Grade Iberico Pork Shabu Shabu Course','Japan','Tokyo','$3 Ramen vs $79 Ramen','3','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('R.O.Star','Bitter Sweet Blend Iced Coffee','Japan','Tokyo','$1 Coffee vs $914 Coffee','3','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Coffee Elementary School','C.E.S. Blend','Japan','Tokyo','$1 Coffee vs $914 Coffee','3','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Münch','22 Year Barrel-Aged Coffee','Japan','Osaka','$1 Coffee vs $914 Coffee','3','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Pablo Coffee','Pablo Cheese Tart','Japan','Osaka','$7 Cake vs $208 Cake','3','10');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Théobroma','San Joaquin Dos','Japan','Tokyo','$7 Cake vs $208 Cake','3','10');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Patisserie Satsuki','Extra Super Melon Shortcake','Japan','Tokyo','$7 Cake vs $208 Cake','3','10');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Pajarito','Queso Fundido','USA','St Paul','$10 Game Day Food vs $456 Game Day Food','3','11');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Revival','Whole Bird Tennessee Hot','USA','Minneapolis','$10 Game Day Food vs $456 Game Day Food','3','11');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Chowgirls Killer Catering','Chowgirls Super Bowl Feast','USA','Minneapolis','$10 Game Day Food vs $456 Game Day Food','3','11');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Cheeky\'s','Bacon Flight','USA','Palm Springs','$2 Bacon vs $100 Bacon','4','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Manuela','BLT','USA','Los Angeles','$2 Bacon vs $100 Bacon','4','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Belly (CLOSED)','Omakase','USA','New York City','$2 Bacon vs $100 Bacon','4','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Utopia Bagels','Regular Bagel','USA','New York City','$1 Bagel vs $1000 Bagel','4','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Bar Bolonat (CLOSED)','Jerusalem Bagel','USA','New York City','$1 Bagel vs $1000 Bagel','4','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Westin','The $1000 Bagel','USA','New York City','$1 Bagel vs $1000 Bagel','4','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Seasoned Vegan','Po\'boy','USA','New York City','$10 Vegan vs $135 Vegan','4','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Avant Garden','4 dishes:,Sunchoke Toast,Avocado,Hen of the Woods,Celery Root','USA','New York City','$10 Vegan vs $135 Vegan','4','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('ABCV','6 dishes:,Green Chickpea Hummus,Grilled Donko Shitake,Slow Roasted Beets,Whole Roasted Cauliflower,Market Carrots,Warm Crimini & Chanterelle Mushrooms','USA','New York City','$10 Vegan vs $135 Vegan','4','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Ahi Assassins','Lunatic/Haiwaiian Style','USA','Honolulu','$9 Fish vs $140 Fish','4','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('MW Restaurant','Mochi-Crusted Onaga','USA','Honolulu','$9 Fish vs $140 Fish','4','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Chef Mavro','Onaga Baked in Salt Crust','USA','Honolulu','$9 Fish vs $140 Fish','4','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Pie \'n Burger','Apple Pie','USA','Pasadena','$5 Pie vs $250 Pie','4','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Underbelly','Carrot Cake Fried Pie','USA','Houston','$5 Pie vs $250 Pie','4','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Three Brothers Bakery','Pumpecapple Piecake','USA','Houston','$5 Pie vs $250 Pie','4','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Pho Binh By Night','Pho Bo','USA','Houston','$7 Pho vs $68 Pho','4','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Pig and the Lady','Pho Bac','USA','Honolulu','$7 Pho vs $68 Pho','4','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('District One Kitchen & Bar','The Original Whole Maine Lobster Pho','USA','Las Vegas','$7 Pho vs $68 Pho','4','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Rice Bar','House-Made Pork Longganisa','USA','Los Angeles','$12 Pork vs $715 Pork','4','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Lasa','Twice Cooked Pork Belly','USA','Los Angeles','$12 Pork vs $715 Pork','4','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Jeepney','Kamayan','USA','New York City','$12 Pork vs $715 Pork','4','7');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Sqirl','Famed Ricotta Toast','USA','Los Angeles','$8 Toast vs $20 Toast','4','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Here\'s Looking at You','Chicken Liver','USA','Los Angeles','$8 Toast vs $20 Toast','4','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Petit Crenn','Mushroom Tartine','USA','San Francisco','$8 Toast vs $20 Toast','4','8');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Barzotto','Extra Long Noodles Spaghetti','USA','San Francisco','$15 Spaghetti vs $143 Spaghetti','4','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Cento Pasta Bar','Beet Spaghetti','USA','Los Angeles','$15 Spaghetti vs $143 Spaghetti','4','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Republique Restaurant','Spaghetti Rustichella','USA','Los Angeles','$15 Spaghetti vs $143 Spaghetti','4','9');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Top Round Roast Beef','Curly Fries','USA','Los Angeles','$3 Fries vs $100 Fries','4','10');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Lov','Kimchi Fries','Canada','Montreal','$3 Fries vs $100 Fries','4','10');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Poutineville','La Crise Cardiaque ('The Heart Attack')','Canada','Montreal','$3 Fries vs $100 Fries','4','10');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('John\'s Roast Pork','Cheesteak ('Onions Provolone')','USA','Philadelphia','$10 Cheesesteak vs $120 Cheesesteak','4','11');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Gin & Pop','Local Mushroom Cheesesteak','USA','Philadelphia','$10 Cheesesteak vs $120 Cheesesteak','4','11');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Barclay Prime','Barclay Prime Cheesesteak','USA','Philadelphia','$10 Cheesesteak vs $120 Cheesesteak','4','11');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Corner 28','Peking Duck Bun','USA','New York City','$2 Peking Duck vs $340 Peking Duck','4','12');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Decoy','Peking Duck','USA','New York City','$2 Peking Duck vs $340 Peking Duck','4','12');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Little One','Matcha Kakigori','USA','New York City','$2 Peking Duck vs $340 Peking Duck','4','12');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Hwa Yuan Szechuan','Beijing Duck 9 Course Tasting Menu','USA','New York City','$2 Peking Duck vs $340 Peking Duck','4','12');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Little Fatty','Chinese BBQ Pork','USA','Los Angeles','$29 vs $180 Family-Style Meats','5','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Freedman\'s','Glazed Brisket','USA','Los Angeles','$29 vs $180 Family-Style Meats','5','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('APL','APL Short Rib','USA','Los Angeles','$29 vs $180 Family-Style Meats','5','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Fay Da Bakery','Curry Beef Puff','USA','New York City','$2 Curry vs $75 Curry','5','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Laut','Roti Canai','USA','New York City','$2 Curry vs $75 Curry','5','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Junoon','3 courses: ,Butter Pepper Garlic Shrimp,Shahi Lamb Shank,The Drunken Shahi Tukra','USA','New York City','$2 Curry vs $75 Curry','5','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Mah-Ze-Dahr Bakery','Vanilla Shortbread','USA','New York City','$1 Cookie vs $90 Cookie','5','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Levain Bakery','Chocolate Chip Walnut Cookie','USA','New York City','$1 Cookie vs $90 Cookie','5','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Antolpo','Icing Cookie','Japan','Japan','$1 Cookie vs $90 Cookie','5','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Kura Sushi','Various Sushi Plates','Japan','Japan','$1 Sushi vs $133 Sushi','5','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Sushi Dokoro Shun','Sushi Platter','Japan','Japan','$1 Sushi vs $133 Sushi','5','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Kyubey','Sushi Degustation','Japan','Japan','$1 Sushi vs $133 Sushi','5','4');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Marutake','Tamagoyaki','Japan','Japan','$1 Eggs vs $89 Eggs','5','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Yoshokuya Kichi Kichi','Ox Tongue Stew','Japan','Japan','$1 Eggs vs $89 Eggs','5','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Aqua Farm Chichibu','Fresh Kagayaki eggs','Japan','Japan','$1 Eggs vs $89 Eggs','5','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Maccha House Kiyomizu-Dera','Maccha Parfe and Tiramisu','Japan','Japan','$1 Eggs vs $89 Eggs','5','5');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Bolton\'s Spicy Chicken & Fish','Breast Quarter Sandwich','USA','Nashville','$6 Sandwich vs $180 Sandwich','5','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Oinkster','Oinkster Pastrami','USA','Los Angeles','$6 Sandwich vs $180 Sandwich','5','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Wagyumafia Cutlet Sandwich','Kobe','Japan','Tokyo','$6 Sandwich vs $180 Sandwich','5','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Pampas Grill','Pão De Queijo','USA','Los Angeles','$710 Potluck Dinner - Holiday Special Part 1','Holiday Special','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('n/a','Kiano\'s Kenyan Beef Samosas','n/a','n/a','$710 Potluck Dinner - Holiday Special Part 1','Holiday Special','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('The Pie Hole','Mom\'s Apple Crumble Pie','USA','Los Angeles','$192 Desserts - Holiday Special Part 2','Holiday Special','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('n/a','Rie\'s Russian Roulette Croquem Bouche','n/a','n/a','$192 Desserts - Holiday Special Part 2','Holiday Special','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('A Cut Above Butcher Shop','Prime Dry Aged Rib Roast 8.47lbs','USA','Los Angeles','$347 Prime Rib - Holiday Special Part 3','Holiday Special','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Sinuiji Chapsal Soonae','Tteokbokki (Spicy Rice Cake)','USA','Los Angeles','$347 Prime Rib - Holiday Special Part 3','Holiday Special','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('n/a','Kwesi\'s Ponche-de-Creme','n/a','n/a','$347 Prime Rib - Holiday Special Part 3','Holiday Special','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Isetan Department Store','Ruby Roman Grapes','Japan','Tokyo','$1977 Japanese Grapes','One Stop','1');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Providence','Seasonal Tasting Menu','USA','Los Angeles','$210 7-Course Seafood Dinner','One Stop','2');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Nikko Masuzushi Honpo','Nikko Buried Treasure Bento','Japan','Nikko','$1593 Bento Box','One Stop','3');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Kings Burger / Got Sushi?','Salmon Nigiri','USA','Los Angeles','$10 Sushi & Burger vs $58 Sushi & Burger','6','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Ototo','Hirame Crudo','USA','Los Angeles','$10 Sushi & Burger vs $58 Sushi & Burger','6','6');
INSERT INTO restaurants (name,notes,country,city,`episode name`,season,episode) VALUES ('Tetsu','Masa Toro Roll','USA','New York City','$10 Sushi & Burger vs $58 Sushi & Burger','6','6');
