# Huge s/o to pauseforasecond for the spreadsheet based on the BuzzFeed show Is It Worth It.
USE javaProjects;
INSERT INTO foods (name, price, `price point`) VALUES ('Bluefin Nigiri',4.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Spciy Scallap Roll',2.950000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Spanish Mackerel',6.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Sweet Shrimp Nigiri',2.950000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Kinmedai White Ponzu;Nigiri Platter;Cajun Crab Roll',18.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Omakase',250.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Double Charburger',4.150000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Hog Burger',18.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('777 Burger',777.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Simple Pie',5.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Green Stripe',7.950000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Squash Blossoms',23.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Italian Summer Truffle',135.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Steak and Eggs',11.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Dry-Aged Rib Eye',72.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Japanese Pure Wagyu',306.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Tagliatella Arrabbiata',8.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Gnocchi Porcini',15.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Spaghetti Bottarga',12.500000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Bigoli Neri Alla Bottarga',19.750000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Pappardelle All\'anatra',19.250000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Flambeed White Truffle Pasta',100.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Kosher Dog',2.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Sweet & Spicy',6.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Lamb with Mediterranean Spices',8.500000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Rattlesnake & Rabbit',8.500000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Juuni Ban',169.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Salmon Fish & Chips',8.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Chinook King Salmon',25.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('King Salmon',56.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Korean BBQ',23.990000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Korean BBQ',65.440000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Korean BBQ',345.910000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Milk\'n Berries Cake',26.750000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Chocolate Espresso Cake',48.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Custom Cake',1120.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Glazed Donut',1.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Black & White Donut',1.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Brioche Donuts',12.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Golden Donut',100.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Buffet Food',8.990000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Buffet Food',49.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Buffet Food',95.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Tacos Al Pastor',1.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Calabacitas;Mole Poblano;Cochinita Pibil',2.750000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Caviar Taco',47.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Small Dipped Cone',1.690000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('One Scoop Brown Bread Maple Black Truffle',3.950000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Golden Opulence Sundae',1000.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Cheese Slice',2.750000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Marinara Pizza',13.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Calzone',18.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('The 24K',2000.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Classic Cheesecake',3.900000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Orange Dream Cheesecake',12.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Gateu Nuage',70.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Peanut Butter Bacon Burger',6.840000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Off-Menu Bacon Burger',29.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Caviar Souffle',2500.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Davey\'s Old Fashioned',6.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Scorpion Bowl',40.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Penicillin',208.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Oolong Tea-Infused Egg',2.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Peeky Toe Crab & Lobster Omelette',18.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Truggle Egg',95.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Beef Rib Finger Meat',13.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Soy Marinated Beef Ribs',28.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Hanwoo \'Byeongpung\' Beef Ribs',256.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Mac & Cheese',3.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Craw Mac Deluxe',13.990000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Truffle Lobster Mac & Cheese',195.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('1/2 lb Pork Spare Ribs',7.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Pork Spare Ribs',36.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Full Rack Pork Spare Ribs',68.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Coffin Bay Oyster;Sydney Rock Oyster',3.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Grilled WA Marren',42.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Braised Whole Green Lip Abalone',213.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('2016 Marsanne',17.950000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Ladies Who Shoot Their Lunch 2016 Shiraz',35.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Museum Muscadelle;Museum Muscat',1000.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('250g Rump Steak with Beans and Mash',16.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('500g Grass Fed T-Bone',63.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Eye of Chuck Wagyu Ox',69.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('300g Sirloin ',150.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Sylvia\'s Down Home Fried Chicken',16.950000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Hot Honey Yard Bird',27.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Caviar & Fried Chicken',500.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Trinity;Blanco;Pecos;Lil Queso;Iced Toddy L',18.750000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('All You Can Drink;All You Can Eat Stacks on Stacks',30.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Brunch Buffet;Free Flow Champagne',113.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Ramen',3.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Shobu Soba',8.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Ultimate Ramen & Highest Grade Iberico Pork Shabu Shabu Course',79.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Bitter Sweet Blend Iced Coffee',1.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('C.E.S. Blend',4.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('22 Year Barrel-Aged Coffee',914.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Pablo Cheese Tart',7.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('San Joaquin Dos',23.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Extra Super Melon Shortcake',208.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Queso Fundido',10.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Whole Bird Tennessee Hot',29.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Chowgirls Super Bowl Feast',456.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Bacon Flight',6.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('BLT',18.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Omakase',100.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Regular Bagel',1.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Jerusalem Bagel',7.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('The $1000 Bagel',1000.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Po\'boy',10.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('4 dishes:;Sunchoke Toast;Avocado;Hen of the Woods;Celery Root',64.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('6 dishes:;Green Chickpea Hummus;Grilled Donko Shitake;Slow Roasted Beets;Whole Roasted Cauliflower;Market Carrots;Warm Crimini & Chanterelle Mushrooms',184.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Lunatic/Haiwaiian Style',9.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Bag of Bones',15.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Mochi-Crusted Onaga',38.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Tropical Fruit Creamsicle Brulee',12.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Onaga Baked in Salt Crust',140.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Apple Pie',4.500000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Carrot Cake Fried Pie',9.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Pumpecapple Piecake',250.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Pho Bo',6.750000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Pho Bac',16.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Mary\'s Free Range Duck Pho',20.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Vegan Pho',16.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('The Original Whole Maine Lobster Pho',67.940000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('House-Made Pork Longganisa',11.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Twice Cooked Pork Belly',21.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Kamayan',715.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Famed Ricotta Toast',8.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Chicken Liver',10.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Stracciatella',16.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Mushroom Tartine',20.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Extra Long Noodles Spaghetti',15.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Porchetta',18.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Beet Spaghetti',18.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Spaghetti Rustichella',143.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Curly Fries',2.990000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Kimchi Fries',8.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('La Crise Cardiaque (The Heart Attack)',100.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Cheesteak (Onions Provolone)',9.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Local Mushroom Cheesesteak',14.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Barclay Prime Cheesesteak',120.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Peking Duck Bun',1.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Peking Duck',85.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Matcha Kakigori',7.000000,9);
INSERT INTO foods (name, price, `price point`) VALUES ('Beijing Duck 9 Course Tasting Menu',340.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Chinese BBQ Pork',29.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Glazed Brisket',105.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('APL Short Rib',180.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Curry Beef Puff',2.250000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Roti Canai',8.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Curry Laksa',15.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('3 courses: ;Butter Pepper Garlic Shrimp;Shahi Lamb Shank;The Drunken Shahi Tukra',75.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Vanilla Shortbread',1.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Chocolate Chip Walnut Cookie',4.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Icing Cookie',90.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Various Sushi Plates',1.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Sushi Platter',44.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Sushi Degustation',133.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Tamagoyaki',1.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Ox Tongue Stew',-1.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Omaurice',24.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Fresh Kagayaki eggs',89.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Maccha Parfe and Tiramisu',-1.000000,9);
INSERT INTO foods (name, price, `price point`) VALUES ('Breast Quarter Sandwich',5.750000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Oinkster Pastrami',11.500000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Kobe',180.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Pão De Queijo',9.250000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Kiano\'s Kenyan Beef Samosas',15.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Mom\'s Apple Crumble Pie',40.500000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Salted Chocolate Pie',42.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Salted Caramel Pecan Pie',42.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Earl Grey Tea Pie',42.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Rie\'s Russian Roulette Croquem Bouche',25.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Prime Dry Aged Rib Roast 8.47lbs',347.190000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Half Pound Grassfed Burger',13.250000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Tteokbokki (Spicy Rice Cake)',10.990000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Kwesi\'s Ponche-de-Creme',-1.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Ruby Roman Grapes',1977.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Seasonal Tasting Menu',210.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Nikko Buried Treasure Bento',1593.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Salmon Nigiri',5.500000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Jr. Cheeseburger',4.090000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Kampachi 3 Way',12.000000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('King\'s Special (Pastrami CB)',8.490000,1);
INSERT INTO foods (name, price, `price point`) VALUES ('Hirame Crudo',23.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Ode To MOS Burger',14.000000,2);
INSERT INTO foods (name, price, `price point`) VALUES ('Masa Toro Roll',35.000000,3);
INSERT INTO foods (name, price, `price point`) VALUES ('Masa\'s Burger',23.000000,3);
